version: '3.7'
services:
  postgres:
    container_name: project_scheduler_postgres
    image: postgres:15
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
      PGDATA: /data/postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_scheduler_network
networks:
  project_scheduler_network:
    driver: bridge