CREATE TABLE "tb_users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(255) NOT NULL,
  "name" VARCHAR(255) NOT NULL,
  "process_id" uuid,
  "status" VARCHAR(255) NOT NULL CHECK ("status" IN ('PENDING', 'PROCESSED')),
  PRIMARY KEY ("id")
);